#!/bin/bash

if [[ -r $HOME/.optional-startup ]]; then
    $HOME/.optional-startup
fi

# wallpaper
feh --bg-fill "$HOME/.wallpaper"

# filter screen
#redshift &
redshift-gtk &

# aria2
aria2c

# volume icon
volumeicon &

# battery icon
cbatticon &

# networkmanager
nm-applet &

# ibus
killall -9 ibus-daemon
ibus-daemon -dx

# Xresource
xrdb -merge "$HOME/.Xresources"

# fix mouse xmonad
xsetroot -cursor_name left_ptr

# set keyboard speed
xset r rate 200 25

# turn off screen after 5 minutes
xset dpms 300

# init lockscreen
xautolock -detectsleep -locker "lockscreen" &

# lock screen after suspend or hibernate
killall -9 xss-lock
xss-lock -- "lockscreen" &

# polkit
lxpolkit &

# udiskie automount
udiskie -C0ansf $(which thunar) &

# notification daemon
dunst &

# clipboad manager
parcellite &

# caffeine
caffeine &

# bluetooth
blueman-applet &

# gnome keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

