#!/bin/bash

if [[ -r $HOME/.optional ]]; then
    $HOME/.optional
fi

# wallpaper
#sleep 1 && feh --bg-fill "$HOME/.wallpaper"
feh --bg-fill "$HOME/.wallpaper"

# conky desktop
#sleep 1 && conky -c "$HOME/.i3/conky/Modern1.0/Modern1.1.0" &

# filter screen
redshift &
redshift-gtk &

# aria2
aria2c

# ibus
ibus-daemon -dx

# Xresource
xrdb -merge "$HOME/.Xresources"

# fix mouse xmonad
xsetroot -cursor_name left_ptr

# set keyboard speed
xset r rate 200 25

# turn off screen after 5 minutes
xset dpms 300

# auto lock screen after 10 minutes
xautolock -detectsleep -time 10 -locker "$HOME/.i3/lock/lock-i3" &

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# udiskie automount
udiskie -C0ansf $(which ranger) &

# notification daemon
dunst &

