#!/bin/bash

# shutdown
if [[ "$1" == "shutdown" ]]; then
	systemctl poweroff -i;
	exit 1;
fi

# restart
if [[ "$1" == "reboot" ]]; then
	systemctl reboot;
	exit 1;
fi

# logout
if [[ "$1" == "logout" ]]; then
	i3-msg exit;
	exit 1;
fi

# Take a screenshot
scrot /tmp/screen_locked.png

# Pixellate it 10x
#mogrify -scale 10% -scale 1000% /tmp/screen_locked.png
convert /tmp/screen_locked.png -blur 0x6 /tmp/screen_locked.png

# Lock screen displaying this image.
i3lock -i /tmp/screen_locked.png

# suspend
if [[ "$1" == "suspend" ]]; then
	systemctl suspend;
	exit 1;
fi

# Turn the screen off after a delay.
sleep 60; pgrep i3lock && xset dpms force off
