#!/bin/bash

# Take a screenshot
xwd -root -silent -out /tmp/screen_locked.xwd

# Pixellate it 10x
convert /tmp/screen_locked.xwd -blur 0x6 /tmp/screen_locked.png

# Lock screen displaying this image.
i3lock -i /tmp/screen_locked.png

